services:
  api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: dms_nestjs
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DB_HOST: postgres_prod
    restart: unless-stopped
    depends_on:
      postgres_prod:
        condition: service_healthy
  postgres_prod:
    image: postgres:16-alpine
    container_name: dms-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dms
    ports:
      - "5432:5432"
    volumes:
      - dms_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dms_prod_data:
